module.exports = [
    {
      cardgame: "Pokemon",
      name: "Charmander",
      set: "Base",
      rarity: "Common",
      value: "90",
      img: "https://product-images.tcgplayer.com/fit-in/437x437/107043.jpg",
    },
    {
      cardgame: "Pokemon",
      name: "Bulbasaur",
      set: "Base",
      rarity: "Common",
      value: "155",
      img: "https://product-images.tcgplayer.com/fit-in/874x874/107041.jpg",
    },
    {
      cardgame: "Pokemon",
      name: "Squirtle",
      set: "Base",
      rarity: "Common",
      value: "80",
      img: "https://product-images.tcgplayer.com/fit-in/437x437/107060.jpg",
    },
    {
      cardgame: "Pokemon",
      name: "Eevee",
      set: "Jungle",
      rarity: "Common",
      value: "6",
      img: "https://product-images.tcgplayer.com/fit-in/437x437/45154.jpg",
    },
    {
      cardgame: "Pokemon",
      name: "Pikachu",
      set: "Base",
      rarity: "Common",
      value: "200",
      img: "https://product-images.tcgplayer.com/fit-in/437x437/107055.jpg",
    },
    {
      cardgame: "Magic",
      name: "Timetwister",
      set: "Alpha",
      rarity: "Rare",
      value: "10000",
      img: "https://product-images.tcgplayer.com/fit-in/437x437/1285.jpg",
    },
    {
      cardgame: "Magic",
      name: "The Hive",
      set: "Alpha",
      rarity: "Rare",
      value: "935",
      img: "https://product-images.tcgplayer.com/fit-in/437x437/1278.jpg",
    },
    {
      cardgame: "Magic",
      name: "The Wandering Emperor",
      set: "Kamigawa: Neon Dynasty",
      rarity: "Mythic",
      value: "166",
      img: "https://product-images.tcgplayer.com/fit-in/437x437/263247.jpg",
    },
    {
      cardgame: "Magic",
      name: "Godless Shrine",
      set: "Unfinity",
      rarity: "Land",
      value: "125",
      img: "https://product-images.tcgplayer.com/fit-in/437x437/287158.jpg",
    },
    {
      cardgame: "Magic",
      name: "Comet, Stellar Pup",
      set: "Unfinity",
      rarity: "Mythic",
      value: "10",
      img: "https://product-images.tcgplayer.com/fit-in/437x437/287142.jpg",
    },
    {
      cardgame: "YuGiOh",
      name: "Blue Eyes White Dragon",
      set: "The Legend of Blue Eyes White Dragon",
      rarity: "Ultra Rare",
      value: "400",
      img: "https://product-images.tcgplayer.com/fit-in/437x437/21792.jpg",
    },
    {
      cardgame: "YuGiOh",
      name: "Dark Magician",
      set: "The Legend of Blue Eyes White Dragon",
      rarity: "Ultra Rare",
      value: "500",
      img: "https://product-images.tcgplayer.com/fit-in/437x437/21876.jpg",
    },
    {
      cardgame: "YuGiOh",
      name: "Tri Horned Dragon",
      set: "The Legend of Blue Eyes White Dragon",
      rarity: "Secret Rare",
      value: "150",
      img: "https://product-images.tcgplayer.com/fit-in/437x437/22538.jpg",
    },
    {
      cardgame: "YuGiOh",
      name: "Bystial Druiswurm",
      set: "Darkwing Blast",
      rarity: "Super Rare",
      value: "8",
      img: "https://product-images.tcgplayer.com/fit-in/437x437/450160.jpg",
    },
  ]